[tool.robotpy]

robotpy_version = "2025.2.1.2"

robotpy_extras = [
    "apriltag",
    "commands2",
    "phoenix6"
]

# Other pip packages to install
requires = [
    "robotpy-pathplannerlib==2025.2.2"
]
